export const SET_FINANCIAL_INFORMATION = "SET_FINANCIAL_INFORMATION";

export const SET_PRODUCT_ID = "SET_PRODUCT_ID";
export const SET_FACILITIES_AMOUNT = "SET_FACILITIES_AMOUNT";
export const SET_INSTALLMENT_PERIOD = "SET_INSTALLMENT_PERIOD";

export const SET_USER_INFORMATION = "SET_USER_INFORMATION";

export const SET_IS_LOADING = "SET_IS_LOADING";
