import Head from "next/head";
import Image from "next/image";
import Link from "next/link";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <input
          placeholder="number / numeric"
          type="number"
          inputMode="numeric"
        />

        <input
          placeholder="number / numeric"
          type="number"
          inputMode="numeric"
        />

        <input placeholder="number / tel" type="number" inputMode="tel" />

        <input placeholder="tel" type="tel" />
        <Link href="/identity">اطلاعات کاربر</Link>
    </div>
  );
}
