import { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    if (router.asPath === "/") {
      window.onpopstate = () => {
        history.go(1);
      };
    }
  }, [router]);

  return (
    <div>
      <Head>
        <title>Create Next App 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input placeholder="number / numeric" type="number" inputMode="numeric" />

      <input placeholder="number / numeric" type="number" inputMode="numeric" />

      <input placeholder="number / tel" type="number" inputMode="tel" />

      <input placeholder="tel" type="tel" />
      <Link href="/identity">اطلاعات کاربر</Link>
    </div>
  );
}
